# Generated by Django 4.1.1 on 2022-10-18 03:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_created_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 18, 3, 47, 58, 687074, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 18, 3, 47, 58, 686576, tzinfo=datetime.timezone.utc)),
        ),
    ]
